version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    assignees:
      - "Stackclash"
    schedule:
      interval: "weekly"
    groups:
      production-dependencies:
        dependency-type: "production"
        applies-to: "version-updates"
        update-types:
          - "minor"
          - "patch"
      production-major-dependencies:
        dependency-type: "production"
        applies-to: "version-updates"
        update-types:
          - "major"
      development-dependencies:
        dependency-type: "development"
        applies-to: "version-updates"
  - package-ecosystem: "github-actions"
    directory: "/"
    assignees:
      - "Stackclash"
    schedule:
      interval: "weekly"