site_name: TTRPG Data Forge
site_url: https://stackclash.github.io/ttrpg-data-forge
repo_url: https://github.com/Stackclash/ttrpg-data-forge
edit_uri: blob/main/docs/
remote_branch: gh-pages
docs_dir: docs
theme:
  name: material
  features:
    - toc.integrate
plugins:
  - include-markdown
markdown_extensions:
  - github-callouts