site_name: TTRPG Data Forge
site_description: Plugin-based CLI framework for collecting and processing TTRPG data
site_url: https://ttrpg-data-forge.github.io/core
repo_url: https://github.com/ttrpg-data-forge/core
edit_uri: blob/main/docs/
remote_branch: gh-pages
docs_dir: docs

theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.path
    - toc.integrate
    - search.highlight
    - search.share

plugins:
  - include-markdown
  - search

markdown_extensions:
  - github-callouts
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: true
  - attr_list
  - md_in_html

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - User Guide:
      - Examples: examples.md
      - Commands: commands/
  - Development:
      - Plugin Development: plugin-development.md
      - API Reference: api-reference.md
      - Architecture: architecture.md
