name: Documentation Deployment 
on:
  push:
    paths:
      - docs/**
      - CHANGELOG.md
      - README.md
    branches: 
      - main
  workflow_dispatch:
permissions:
  contents: write
jobs:
  docs-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - uses: actions/setup-python@v6
        with:
          python-version: 3.x
          cache: 'pip'

      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV

      - run: pip install -r docs/requirements.txt
    
      - run: mkdocs gh-deploy --no-history --force