name: Quality Gates

on:
  pull_request:
    branches:
      - main

jobs:  
  lint:
    name: Lint Codebase
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: latest
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
        
      - name: Run ESLint
        run: npm run lint

  unit-tests:
    name: Unit Tests
    strategy:
      matrix:
        os: ['ubuntu-latest', 'windows-latest']
        node_version: [lts/-1, lts/*, latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node_version }}
          cache: npm

      - run: npm ci

      - run: npm run build
      
      - run: npm run test